- agents/ansari.py
- requirements.txt
- util/prompt_mgr.py
Added logging through langfuse.
> Add logging through langfuse

- .github/workflows/python-app.yml
- agents/ansari.py
- main_api.py
- resources/templates/ask_question.txt
- tests/test_answer_quality.py
- tests/test_main_api.py
- tools/search_quran.py
As-Salamu Alaikum brother M Waleed. 
This pull request begins implementing continuous integration, addressing [issue #6](https://github.com/waleedkadous/ansari-backend/issues/6).
**Tasks:** 
I'd appreciate input on the code changes. Thank you!
> Add Continuous Integration Support

- .github/workflows/python-app.yml
- agents/ansari.py
- tests/test_main_api.py
- tools/search_mawsuah.py
Key changes:
- New search_mawsuah tool
- Ansari agent integration
> Integrate search_mawsuah with Ansari agent

- ansari_db.py
- main_api.py
- sql/06_alter_user_tokens.sql
- sql/06_create_refresh_tokens.sql
- sql/07_create_refresh_tokens.sql
- tests/test_main_api.py
This pull request enhances the user experience by implementing refresh tokens with rotation. With this new approach, users are no longer required to log out and log back in when their login token expires. Instead, the front-end seamlessly handles refreshing the login token using the updated `refresh_token` API.
Here's an overview of the new authentication workflow:
1. **(Front-end)** Login request with valid credentials.
2. **(Back-end)** Login and refresh tokens are returned in the response.
3. **(Front-end)** Securely stores the refresh token.
4. **(After some time, the login token expires)**
5. **(Front-end)** Sends a request to an endpoint requiring authorization.
6. **(Back-end)** Responds with a 401 Unauthorized status.
7. **(Front-end)** Sends a POST request to the `refresh_token` …
> Introducing Refresh Tokens with Rotation for a Seamless User Experience

- ansari_db.py
- main_api.py
- requirements.txt
- tests/test_main_api.py
- Introduced database connection pooling to enhance reliability and prevent issues from a single connection failure.
- Refactored token validation by splitting it into several functions for improved readability and maintainability.
- Implemented caching to handle concurrent refresh token requests, thereby preventing race conditions.
- Added `diskcache` to the requirements.
- Created new test cases to cover the refresh token changes and ensure functionality.
Could you please review the pull request, especially the caching logic?
> Implement refresh token caching to prevent race conditions

- src/ansari/resources/templates/password_reset.html
The password reset link in the template is incorrect.
> Fix password reset link

- src/ansari/presenters/whatsapp_presenter.py
- src/ansari/util/general_helpers.py
Introduces a function to convert conventional markdown to WhatsApp's markdown syntax. Adds a utility to determine the text direction (LTR or RTL) from the message. Enhances logging for request sending and response handling.
Improves message formatting and ensures compatibility with WhatsApp's markdown.
> Adds WhatsApp markdown conversion and language direction detection

- sql/12_alter_user_id_to_uuid.sql
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
This PR covers the following:
**Convert the users ID field from an integer into a UUID**
This is done primarily for security reasons. A migration script '12_alter_user_id_to_uuid.sql' has been added that can migrate both new and existing databases to the updated structure, one thing to note is that the original SQL scripts used 'no action' referential integrity while some of the later scripts switched to 'on delete cascade' (scripts 6, 7, 8) This migration script maintains a strict 'no action' for all foreign keys that reference the users table.
User IDs that are included in access tokens going forward will be in a UUID format instead of an integer format that is prone to enumeration vulnerabilities.
**JWT Before**
**JWT After**
Note that this version will issue 401 for tokens that don't …
> Update user model and APIs

- .env.example
- requirements.txt
- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_claude.py
- src/ansari/app/main_stdio.py
- src/ansari/config.py
- src/ansari/presenters/stdio_presenter.py
- src/ansari/resources/prompts/system_msg_claude.txt
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_quran.py
- src/ansari/tools/search_vectara.py
This PR adds support for using Claude as the LLM backend for Ansari. 
This also involves adding support for citations from Quran, Hadith and the Fiqh Encyclopedia. The implementation is complex because it's no longer using litellm, it is using Anthropic's direct APIs. This is necessary to get things like citations to work correctly. 
It also required a slight modification to the prompt. It also explains its thinking mroe. 
There's a new setting, AGENT, that allows you to choose Ansari (ChatGPT) or AnsariClaude (Claude).
> Add support for a Claude-based Ansari

- pytest.ini
- sql/13_add_ref_list_column.sql
- src/ansari/agents/__init__.py
- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_claude.py
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
- src/ansari/app/main_stdio.py
- src/ansari/config.py
- src/ansari/presenters/api_presenter.py
- src/ansari/presenters/stdio_presenter.py
- src/ansari/presenters/whatsapp_presenter.py
- tests/integration/README.md
- tests/integration/test_ansari_generic.py
- tests/integration/test_ansari_integration.py
- tests/integration/test_claude_integration.py
- tests/integration/test_helpers.py
Add extensive testing to ensure in-db version of conversation history matches in-memory version. 
Note: there is still a bug that I think I need to fix in the frontend. For some reason, the first user message and the first response is a bit messed up. The first user message disappears. The second one looks like this: 
Subsequent results are fine, though.
> Improve Claude implementation

- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_claude.py
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
- src/ansari/app/main_stdio.py
- src/ansari/config.py
- src/ansari/presenters/api_presenter.py
- src/ansari/tools/base_search.py
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_quran.py
- src/ansari/tools/search_tafsir_encyc.py
- src/ansari/tools/search_usul.py
- src/ansari/tools/search_vectara.py
- tests/integration/test_ansari_generic.py
- Added new search tools for the Encyclopedia of Quranic Interpretation
- Implemented message logging fixes in AnsariClaude to ensure consistent history between message logger and agent
- Improved message handling and document formatting for Claude compatibility
- Fixed various bugs and improved error handling throughout the codebase
- Created `BaseSearchTool` abstract class to standardize search tool interfaces
- Added `SearchUsul` class as a base tool for interacting with the Usul.ai API
- Implemented `SearchTafsirEncyc` tool for searching the Encyclopedia of Quranic Interpretation
- Added configuration settings for Usul.ai API integration
- Fixed message logging for tool results - added missing logging calls after adding tool result messages to history
- Improved document format …
> Add Usul Fiqh and Tafsir Encyclopedia Search Tools

- src/ansari/ansari_logger.py
- src/ansari/app/print_search_results.py
- src/ansari/tools/search_quran.py
- src/ansari/tools/search_tafsir_encyc.py
- src/ansari/tools/search_usul.py
- Replace loguru with standard Python logging
- Add print_search_results.py command line tool for direct testing of search tools
- Update search tool logging to use module names
- Fix tafsir encyclopedia search tool formatting
- Enhance usul search to fetch and combine all pages automatically
> Refine tools and add print_search_results utility

- .env.example
- .github/workflows/deploy-staging.yml
- requirements.txt
- src/ansari/app/main_api.py
- src/ansari/config.py
I have created two Sentry projects to track frontend and backend exceptions, this PR covers the backend a a seperate PR will be submitted soon for the frontend.
I have also added an ENVIRONMENT env variable that is currently used by Sentry to segment exceptions based on environment, that value is already defined in the staging workflow, and it will need to be added manually to the production enviornment.
> Integrate Sentry

- sql/00_create_schema.sql
- sql_to_prod/14_integrate_whatsapp_to_main_tables.sql
- src/ansari/agents/ansari_claude.py
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
- src/ansari/app/main_whatsapp.py
- src/ansari/presenters/whatsapp_presenter.py
- tests/integration/test_ansari_integration.py
- tests/integration/test_claude_integration.py
Rename 'webpage' to 'web' in source_type ENUM for consistency 
Add default 'web' source to relevant table columns 
Update function signatures to include source parameter defaulting to WEB (for backward compatibility. I.e., not having to simulatenously update frontend repo) 
Enhance error handling for validation
> Refactor source_type usage in DB/ansari_db.py

- CLAUDE.md
- src/ansari/agents/ansari_claude.py
- Adds comprehensive logging throughout the Claude message processing flow to debug issues with assistant messages not being added to message history
- Adds detailed error tracking for API connections, stream handling, and message validation
- Improves error handling to help diagnose production-specific issues
- Verify logs appear in development environment when running through Claude interaction flow
- Deploy to production environment and check logs for the specific failure point
> Add detailed logging for Claude message history debugging

- sql_to_prod/14_integrate_whatsapp_to_main_tables.sql
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
- src/ansari/presenters/whatsapp_presenter.py
Removed custom CORS validation checks and retained the FastAPI CORS middleware.  
Updated the refresh token handling logic to prevent invalidating the old refresh token.
> Remove Custom CORS Validation and Update Refresh Token Handling Logic

- CLAUDE.md
- src/ansari/agents/ansari_claude.py
- Added a new "Repository Organization" section to CLAUDE.md with guidelines for keeping the repository clean
- Specifically instructs developers to place temporary files and debug scripts in the tmp/ directory
- Clarifies that tmp/ is gitignored and ideal for development-only files
- No tests needed for documentation changes
> Add repository organization guidelines to documentation

- CLAUDE.md
- src/ansari/agents/ansari_claude.py
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_quran.py
- tests/integration/test_ansari_generic.py
- tests/integration/test_ansari_integration.py
- tests/unit/test_citation_formatting.py
- tests/unit/test_search_mawsuah.py
- tests/unit/test_search_tafsir_encyc.py
- Fix termination issue by properly handling tool_use stop_reason in message_delta events
- Improve code readability with clear section comments in process_one_round
- Add safety check to prevent infinite loops in process_message_history
- Update documentation to be more accurate
- Fix citation handling to ensure consistent formatting:
- Update search tools to format data as JSON for citations
- Handle both JSON and plain text in citation processing
- Fix tests to verify proper citation formatting
- Update documentation with citation guidelines
- Verified all existing tests pass (test_ansari_claude_message_sequence.py, test_ansari_claude_tool_sequence.py, test_logging_regression.py)
- Added more robust tests for citation formatting
- Changed behavior should now properly handle tool calls …
> Refactor process_one_round and fix tool_use termination

- src/ansari/ansari_db.py
- tests/unit/test_message_id_in_thread.py
- Modified database queries to include message IDs
- Updated conversion functions to handle and include message IDs in responses
- Added test to verify message IDs are properly included
> Add message ID in thread responses to support thumbs up/down

- src/ansari/agents/ansari_claude.py
This PR aims to resolve the invalid json and encoded text rendering in the citations text, specifically this issue:
My observations working with the Anthropic APIs is that they only accept plain text when submitting tool results back, however the results we recieve from search_quran and search_hadith are json formatted, when I tried to inform Anthropic that the text is json formatted, it threw this error:
So I updated have the pipeline to pre-process json and extract plain text content up-front, this is the process that currently takes place at the finishing step (_finish_response), the issue I have noticed when we wait until this phase is that sometimes the response contains invalid json (even though the original json returned from the tool is valid), probably because Claude considers …
> Update Claude citation handling

- docs/impl/mongodb.md
- docs/spec/mongodb.md
- Add MongoDB migration specification outlining the change from SQL to MongoDB for threads
- Create detailed implementation plan with schema design, API changes, and migration strategy
- No code changes yet, documentation only
> MongoDB Migration Spec and Implementation Plan

- .github/workflows/python-app.yml
- src/ansari/agents/ansari_claude.py
- src/ansari/cli/use_tools.py
- src/ansari/tools/base_search.py
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_mawsuah.py
- src/ansari/tools/search_quran.py
- src/ansari/tools/search_tafsir_encyc.py
- src/ansari/tools/search_usul.py
- src/ansari/tools/search_vectara.py
- src/ansari/util/general_helpers.py
Address the issues with the Anthropic client not accepting titles longer than 500 characters.
> Fix long citations

- pyproject.toml
- src/ansari/ansari_db.py
- uv.lock
Resolves alert https://github.com/ansari-project/ansari-backend/security/dependabot/7
> Resolve LiteLLM security alert

- src/ansari/ansari_db.py
- src/ansari/cli/use_tools.py
This PR fixes a silly bug in the codebase by updating the ansari_db.py and use_tools.py files.
> Fix silly bug

- .env.example
- src/ansari/app/main_api.py
- src/ansari/config.py
How's this approach for the app check endpoint? That's the API that the frontend (web and mobile) would call on application startup.
> Implement app check API

- update_database.py
This is the script that was used to identify and update threads with empty message blocks, it has already been executed, I am just adding it as a reference.
> Update documents with empty message blocks

- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
Add support for the newly created frontend env vars.
> Update deployment workflows

- src/ansari/app/main_api.py
Some of the APIs are currently re-raising 400 to 403 exceptions as 500 internal server errors preventing the frontend from displaying user friendly messages like 'accounts already exists', 'password is too weak' etc.
The sample request below is supposed to return an account already exists error.
> Raise HTTPExceptions without changing status code

- src/ansari/config.py
- Updated the default Anthropic model from `claude-3-7-sonnet-latest` to `claude-sonnet-4-20250514`
- This upgrades the Ansari backend to use Claude Sonnet 4, the latest model version
- Modified `ANTHROPIC_MODEL` setting in `src/ansari/config.py`
- Deploy to staging environment
- Test that the AnsariClaude agent works correctly with the new model
- Verify responses are being generated as expected
> Update Anthropic model to Sonnet 4

- src/ansari/app/main_api.py
- tests/unit/test_mcp_endpoint.py
- Renamed endpoint from `/api/v2/mcp` to `/api/v2/mcp-complete`
- Added critical attribution message to all responses stating information came from ansari.chat
- Updated all tests to use the new endpoint name
- Updated endpoint path in `main_api.py`
- Added attribution wrapper to streaming response
- Updated all test cases to use new endpoint name
> Rename MCP endpoint and add attribution message

- src/ansari/app/main_api.py
- tests/unit/test_ayah_claude_endpoint.py
This PR adds a new `/api/v2/ayah-claude` endpoint that provides the same functionality as the existing `/api/v2/ayah` endpoint but uses AnsariClaude instead of AnsariWorkflow for enhanced reasoning and citation capabilities.
- **AnsariClaude Integration**: Leverages AnsariClaude's advanced reasoning and citation handling
- **Feature Parity**: Maintains all key features from the original endpoint:
- API key authentication using `QURAN_DOT_COM_API_KEY`
- Ayah-specific system prompt for specialized responses
- Database caching for response optimization
- Tafsir search with ayah-specific filtering
- Support for `augment_question` parameter
- JSON response format (non-streaming)
- Added new `/api/v2/ayah-claude` endpoint in `main_api.py`
- Created comprehensive unit tests in …
> Add /api/v2/ayah-claude endpoint using AnsariClaude

- src/ansari/app/main_api.py
- Prepend instruction for brief, concise answers without references
- Update attribution message to mention references available on request
- Responses are ~10x shorter by default, with full citations when requested
- Maintains backward compatibility with existing MCP integrations
> Add concise response mode to MCP endpoint

- .env.example
- .gitignore
- docs/fastapi/async_performance_optimization_strategies.md
- docs/fastapi/sync_vs_async_fastapi_endpoints.md
- src/ansari/agents/ansari_claude.py
- src/ansari/app/main_whatsapp.py
- src/ansari/presenters/whatsapp_presenter.py
- src/ansari/util/debug_utils.py
This PR addresses a critical event loop safety issue in the translation processing system. Previously, the `asyncio.run(...)` calls in translation functions would fail when executed within async contexts (such as WhatsApp background tasks), causing runtime errors.
**Key Improvement**: The existing `_translate_with_event_loop_safety()` method in `ansari_claude.py:1479` has been enhanced and thoroughly documented. This method intelligently handles both synchronous and asynchronous execution contexts:
- **Sync Contexts** (API endpoints): Uses `asyncio.run()` for parallel translation processing
- **Async Contexts** (WhatsApp background tasks): Falls back to sequential processing to avoid event loop conflicts
The issue stems from fundamental differences in how FastAPI handles synchronous vs …
> Event Loop Safety Enhancement and FastAPI Documentation
