ansari-project/ansari-backend

- ansari_db.py
This pull request addresses a minor issue with logging in the `get_thread()` function of the `ansari_db.AnsariDB` class. 
The previous logging statement used an incorrect format, which led to `TypeError: not all arguments converted during string formatting`.
I've updated the logging statement to use an f-string for proper string formatting. 
With this tiny fix, the logging in the `get_thread()` function now works as expected.
> Fix logging error in ansari_db.get_thread()

- data/mawsuah/README.md
- data/mawsuah/strip_tashkeel.py
This PR introduces a script to preprocess Arabic text from 'The Kuwaiti Encyclopaedia of Islamic Jurisprudence', removing diacritics to optimize its use with Vectara models. This change aims to enhance semantic search capabilities.
Following Waleed's feedback, it also includes clear instructions in the README.md on how reproduce the data. This ensures maintainability and the ability to reconstruct the dataset if necessary.
> Add script for Arabic diacritic stripping, and a README

- .env.example
- .gitignore
- README.md
- ansari_db.py
- main_api.py
- setup_database.py
1. Update CORS Logic
2. Add Commit after Insert Snapshot Record
3. Deserialize Snapshot Data before Return in the Response
4. Add Script to execute sql files that create required database tables
> Fix the Issue with the Snapshot API

- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_workflow.py
- src/ansari/app/main_api.py
- src/ansari/app/main_file.py
- src/ansari/config.py
- src/ansari/presenters/ayah_file_presenter.py
- src/ansari/resources/prompts/system_msg_ayah.txt
- src/ansari/resources/prompts/system_msg_ayah_lay.txt
- tests/test_answer_quality.py
- tests/test_main_api.py
Improved the responses in the case of ayah requests. Added more utilities for evaluation.
> Improved ayah mode support

- requirements.txt
- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
This PR accompanies the frontend PR that was recently merged. 
The frontend version disables capitalization of emails during data input and this PR enforces lowercase normalization across the database layer.
One thing that will need to be done before pushing this update to production is to lowercase all user emails and eliminate possible email duplicates (due to different casing).
If there are no duplicates in the database, an update query as simple as this should do the trick:
`update public.users set email = trim(lower(email))`
However, if there are duplicates, this query will fail with duplicate key value violation as the email field has  a unique constraint.
A group by query can be used to identify duplicate emails:
`select trim(lower(email)) as normalized_email from public.users …
> Validate and normalize emails

- .github/workflows/deploy-staging.yml
- Dockerfile
This PR introduces a standalone backend staging environment which complements the frontend staging environment created earlier. 
We now have an end to end isolated environment for testing, the staging frontend CI/CD pipeline (centralized in Expo) has been updated to use the staging backend as shown below.
To prepare for this update, I have made the following changes to the repo:
1. Created a develop branch and set it as the default branch.
2. Added a ruleset that requires at least one reviewer before allowing merging to take place.
3. Merged the user ID changes from integer to UUID into the develop branch.
4. This PR introduces a workflow that will be triggered on pushes to the develop branch to deploy to the staging environment.
Team members will need to do the following changes to their …
> Add staging CI/CD workflow

- src/ansari/app/main_api.py
- src/ansari/app/main_api_client.py
- Created a new filter_message_content function to remove tool results and documents from API responses
- Applied filtering to /api/v2/threads/{thread_id} endpoint
- Applied filtering to /api/v2/share/{share_uuid_str} endpoint
- Made filtering optional with a filter_content parameter (default: true)
- Messages with no text content are completely removed
- Improves API response readability for clients only interested in text content
> Add filtering for tool results and documents in API responses

- CLAUDE.md
- requirements.txt
- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_claude.py
- src/ansari/ansari_db.py
- src/ansari/ansari_logger.py
- src/ansari/app/print_search_results.py
- src/ansari/examples/test_search_mawsuah.py
- src/ansari/tools/base_search.py
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_mawsuah.py
- src/ansari/tools/search_quran.py
- src/ansari/tools/search_tafsir_encyc.py
- src/ansari/tools/search_usul.py
- src/ansari/util/translation.py
- tests/integration/test_ansari_generic.py
- tests/integration/test_ansari_integration.py
- tests/integration/test_claude_integration.py
- tests/integration/test_helpers.py
- tests/unit/__init__.py
- tests/unit/test_ansari_claude_message_sequence.py
- tests/unit/test_ansari_claude_tool_sequence.py
- tests/unit/test_convert_message_llm.py
- tests/unit/test_main_api.py
- tests/unit/test_multilingual_citations.py
- tests/unit/test_search_mawsuah.py
- tests/unit/test_search_tafsir_encyc.py
- tests/unit/test_translation.py
- Adds JSON-based multilingual data structure to document citations
- Prevents duplicate translations for search tools with built-in translations (Quran, Hadith)
- Only translates content when necessary, improving efficiency
- Adds comprehensive tests and updates documentation
1. Run the new tests: ============================= test session starts ==============================
platform darwin -- Python 3.13.2, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/mwk/Development/ansari-project/ansari-backend
configfile: pytest.ini
plugins: asyncio-0.25.3, anyio-4.8.0, timeout-2.3.1, mock-3.14.0
asyncio: mode=Mode.STRICT, asyncio_default_fixture_loop_scope=function
collected 6 items
tests/unit/test_multilingual_citations.py ......                         [100%]
============================== 6 …
> Add multilingual citation support to prevent duplicate translations

- .gitignore
- src/ansari/ansari_db.py
Refactor the message retrieval logic in `ansari_db.py` regarding whatsapp messages to retrieve the correct tool messages format when a whatsapp thread is retrieved from DB (i.e., user sends more than one message in a 3-hour time frame).
> Fix WhatsApp Message Retrieval Logic for Tool Messages

- src/ansari/agents/ansari_claude.py
- src/ansari/cli/use_tools.py
- src/ansari/tools/search_hadith.py
- src/ansari/tools/search_quran.py
- tests/unit/test_citation_formatting.py
- Fixed a bug where JSON was appearing in the Arabic and English fields of Quran citations
- Modified search_quran.py to only store Arabic text in document data
- Updated citation handling to always translate Arabic text to English
- Added extra newlines between Arabic and English in citation output for better readability
- Test by querying 'what does the quran say about sleeplessness?' and verify no JSON appears in citations
> Fix bug with JSON in citations for Quran searches

- src/ansari/agents/ansari_claude.py
- tests/unit/test_ansari_claude_message_sequence.py
- tests/unit/test_logging_regression.py
- Fixed issue with message completion handling that affects production environments
- Added proper handling for both message_stop (local) and message_delta with end_turn (production)
- Prevents duplicate assistant messages by tracking response completion state
- Ran existing unit tests to confirm functionality works
- Manual testing shows the fix properly handles message completion in production
This PR fixes a critical issue where conversations in production would become corrupted or terminated early because the LLM client code was only handling message_stop events but not the end_turn stop_reason in message_delta events.
> Fix Claude response completion handling for both local and production environments

- CLAUDE.md
- LICENSE
- MANIFEST.in
- README.md
- pyproject.toml
- requirements.txt
- src/ansari/agents/ansari_claude.py
- src/ansari/app/main_api_client.py
This PR prepares the ansari-backend package for distribution via PyPI, allowing users to install it with `pip install ansari-backend`. This is primarily so that other projects (e.g. Haadi) can use Ansari directly (without having to do multiple hops). 
- Update `pyproject.toml` with complete package metadata:
- Add dependencies from requirements.txt
- Add project classifiers and license info
- Define CLI entry point: `ansari = "ansari.app.main_stdio:main"`
- Add MIT license file
- Create MANIFEST.in to include non-Python files (templates, prompts)
- Fix linting issues in codebase
- Add installation and usage instructions to README.md
- Successfully built package with `python -m build`
- Verified package includes all necessary files
- Confirmed entry point script works as expected
> Add PyPI packaging support

- src/ansari/agents/ansari_claude.py
- The database now includes message IDs in thread responses for thumbs up/down functionality
- However, these message IDs shouldn't be sent to Claude as they are internal identifiers
- Fixed by cleaning message history before sending to Claude API
- Messages sent to Claude no longer contain ID fields
- Message history returned to clients still contains IDs for UI features
> Remove message IDs before sending to Claude API

- tests/unit/test_message_id_in_thread.py
- Add unit tests to verify that message IDs are properly removed before sending to Claude API
- Tests ensure we don't accidentally send internal message IDs to the AI model
- Test directly verifies that IDs are removed from messages in the replace_message_history method
- Test is isolated from external APIs for fast and reliable execution
> Add tests for message ID removal in Claude

- src/ansari/ansari_db.py
Message.id is a string, the update query was assuming it was an ObjectId thus it wasn't producing a match.
> Resolve thread feedback setting bug

- .gitignore
- docs/fastapi/async_await_backgroundtasks_logs_for_tracing.log
- docs/fastapi/async_await_backgroundtasks_visualized.md
- docs/structure_of_api_responses/anthropic_api_structure_of_message_history.json
- docs/structure_of_api_responses/anthropic_api_structure_of_response.json
- docs/structure_of_api_responses/openai_api_structure_of_chat_completion_chunk_object.ipynb
- src/ansari/agents/ansari.py
- src/ansari/agents/ansari_claude.py
- src/ansari/ansari_logger.py
- src/ansari/app/main_whatsapp.py
- src/ansari/config.py
- src/ansari/presenters/whatsapp_presenter.py
- tests/unit/test_ansari_claude_message_sequence.py
- tests/unit/test_ansari_claude_tool_sequence.py
Main description mentioned here: https://github.com/ansari-project/ansari-backend/commit/670d928f50579562894b6e0939b100d6c9abffe9
(Note: Directly after merging this PR, the WHATSAPP_API_VERSION env. var should be set to `V22.0` instead of `V21.0`).
> Fixed WA's Inf. Loop Msgs | Validated Claude's msg_hist | Added Typing Indicator

- src/ansari/agents/ansari_claude.py
- src/ansari/resources/prompts/system_msg_claude.txt
- src/ansari/util/robust_translation.py
- tests/unit/test_multilingual_data_parsing.py
- Added tool usage tracking to limit excessive tool calls
- Implements two types of limits: max 3 consecutive calls to same tool, max 5 total tools per query
- Added validation and repair for tool_use/tool_result message relationships
- Ensures all tool_result blocks have document blocks to prevent Claude API errors
- Enhanced error handling for tool calls with proper fallbacks
- Test tool usage with queries that would trigger multiple tool calls
- Verify tool limits are enforced (same tool > 3 times, total tools > 5)
- Test message history validation fixes API errors related to missing document blocks
> Implement tool usage tracking with limits and validation

- .env.example
- .github/workflows/deploy-production.yml
- .github/workflows/deploy-staging.yml
- src/ansari/app/main_api.py
- src/ansari/config.py
- src/ansari/resources/templates/password_reset.html
The reset password html template was hardcoded to use the production frontend URL https://ansari.chat which was breaking the reset password flow in the staging environment, this PR introduces a frontend env variable which can be adjusted across staging and prod (I have updated the AWS parameter store accordingly).
> Update the reset password template to use the relevant environment frontend URL

- src/ansari/agents/ansari_claude.py
- Added ephemeral cache control to the last message sent to Claude API
- This enables prompt caching optimization for better performance and cost efficiency
- Modified `process_one_round` method in `src/ansari/agents/ansari_claude.py`
- Adds `cache_control: {type: "ephemeral"}` to all content blocks in the last message
- Handles both list and string content formats properly
- Includes debug logging to track when cache control is added
According to Anthropic's documentation, adding cache control to messages allows the API to cache and reuse prompt prefixes across requests, improving response time and reducing costs.
- Deploy to staging and verify that:
- The AnsariClaude agent continues to work correctly
- No errors occur when processing messages
- Cache control is properly added (check …
> Add prompt caching with ephemeral cache control

- src/ansari/ansari_db.py
- src/ansari/app/main_api.py
- tests/unit/test_mcp_endpoint.py
- Added a new  endpoint for Model Context Protocol integrations
- The endpoint provides unauthenticated access with proper source tracking
- All MCP traffic is tracked with a dedicated SourceType for analytics
- Added Error: typer is required. Install with 'pip install mcp[cli]' to the  enum in 
- Created  endpoint in  that:
- Does not require authentication (no token validation)
- Includes citations in the response
- Uses MCP as the source type for message logging
- Creates thread IDs with format: 
- Uses a system user ID: 
- Added comprehensive unit tests in 
- Created unit tests covering:
- Endpoint existence and accessibility
- No authentication requirement
- Message handling and streaming response
- MCP source type usage
- Error handling for invalid inputs
- Integration with …
> Add MCP endpoint for unauthenticated API access

- src/ansari/agents/ansari_claude.py
- src/ansari/app/main_api.py
- src/ansari/config.py
- tests/unit/test_ansari_claude_system_prompt.py
- tests/unit/test_ayah_claude_fix.py
- Fix FileNotFoundError in /api/v2/ayah-claude endpoint by using PromptMgr
- Add system_prompt_file parameter to AnsariClaude for configurable prompts
- Update process_one_round to use configurable system prompt file
- Migrate Usul API URL from semantic-search.usul.ai to api.usul.ai
- Add comprehensive tests for system prompt file functionality
Fixes:
- Internal server error (500) on ayah-claude endpoint
- SSL certificate error (526) with old Usul API domain
> Fix ayah-claude endpoint and migrate to new Usul API URL

- src/ansari/config.py
- tests/unit/test_ansari_claude_model_version.py
Updates AnsariClaude to use the latest Sonnet 4.5 model (claude-sonnet-4-5-20250929) instead of Sonnet 4 (claude-sonnet-4-20250514).
- Updated `ANTHROPIC_MODEL` configuration in `config.py` to use `claude-sonnet-4-5-20250929`
- Added comprehensive test suite in `tests/unit/test_ansari_claude_model_version.py` to verify:
- AnsariClaude instance uses the correct model version
- The correct model is sent to the Anthropic API during requests
- Default Settings configuration properly sets Sonnet 4.5
> Update AnsariClaude to use Sonnet 4.5
